/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class Carga extends javax.swing.JFrame implements Runnable{
    Thread hc;
    public Carga() {
        initComponents();
        setLocationRelativeTo(null);
        hc = new Thread(this);
        hc.start();
        setVisible(true);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("ImanegesMenuBar/Untitled (6).png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraPro = new javax.swing.JProgressBar();
        txtBarra = new javax.swing.JLabel();
        fondoCarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 300));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraPro.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        barraPro.setOpaque(false);
        jPanel1.add(barraPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 290, 20));

        txtBarra.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 170, 20));

        fondoCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo - Carga.jpg"))); // NOI18N
        jPanel1.add(fondoCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void run(){
        Thread current =  Thread.currentThread();

        while(current==hc){
            for (int i = 0; i < 100; i++) {
                try {
                    Thread.sleep(150);
                } catch (InterruptedException ex) {
                }
                barraPro.setValue(i);
                
                if(i>0){
                    txtBarra.setText("Espere");
                    barraPro.setStringPainted(true);
                    if(i>5 && i<10){
                        txtBarra.setText("Cargando Componentes.");
                        barraPro.setStringPainted(true);
                    }
                    if(i==10){
                        txtBarra.setText("Cargando Componentes.");
                        barraPro.setStringPainted(true);
                        try {
                            Thread.sleep(600);
                        } catch (Exception e) {
                        }
                        i=24;
                    }
                    if(i==25){
                        txtBarra.setText("Cargando Componentes...");
                        barraPro.setStringPainted(true);
                        try {
                            Thread.sleep(600);
                        } catch (Exception e) {
                        }
                        i=49;
                    }
                    
                    if(i==50){
                        txtBarra.setText("Cargando Componentes....");
                        barraPro.setStringPainted(true);
                        try {
                            Thread.sleep(600);
                        } catch (Exception e) {
                        }
                        i=74;
                    }
                    
                    if(i==75){
                        txtBarra.setText("Cargando Componentes.....");
                        barraPro.setStringPainted(true);
                        try {
                            Thread.sleep(800);
                        } catch (Exception e) {
                        }
                        i=89;
                    }
                    if(i==90){
                        txtBarra.setText("Iniciando Aplicación..");
                        barraPro.setStringPainted(true);
                        try {
                            Thread.sleep(800);
                        } catch (Exception e) {
                        }
                        i=98;
                    }
                    if(i==99){
                        barraPro.setStringPainted(true);
                        i=100;
                        txtBarra.setText("Completado!!");
                        try {
                            Thread.sleep(800);
                        } catch (Exception e) {
                        }
                        
                    }
                }else{
                    txtBarra.setText(i + " %  Espere...");
                }
                try {
                    Thread.sleep(40);
                } catch (InterruptedException ex) {
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }
            setVisible(false);
//            VentanaPrincipal principal = new VentanaPrincipal();
//            principal.setVisible(true);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        try {
//            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
//        } catch (ClassNotFoundException ex) {
////            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
////            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
////            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
////            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
//        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraPro;
    private javax.swing.JLabel fondoCarga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtBarra;
    // End of variables declaration//GEN-END:variables
}
