/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author jahir
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        imagenRegistro = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        cajaNombresUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cajaApellidosUsuario = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JLabel();
        cajaUsuarioRg = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JLabel();
        cajaPasswordRg = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setMinimumSize(new java.awt.Dimension(400, 600));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UserRegister.png"))); // NOI18N
        panel.add(imagenRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtNombre.setText("Nombres:");
        panel.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 300, -1));
        panel.add(cajaNombresUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Apellidos:");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 300, -1));
        panel.add(cajaApellidosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 300, 30));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtUsuario.setText("Usuario");
        panel.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 300, -1));
        panel.add(cajaUsuarioRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 300, 30));

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtContraseña.setText("Contraseña:");
        panel.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 300, -1));
        panel.add(cajaPasswordRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 300, 30));

        btnRegistrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        panel.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombreT = "";
        String apellidoT = "";
        String UserR = "";
        String ContraReg = "";

        nombreT = cajaNombresUsuario.getText();
        apellidoT = cajaApellidosUsuario.getText();

        for(int i=0;i<cajaPasswordRg.getPassword().length;i++){
            ContraReg += cajaPasswordRg.getPassword()[i];
        }

        JOptionPane.showMessageDialog(null, "Usuario Registrado Correctamente");

        IniciarSesion ingrese = new IniciarSesion();
        ingrese.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField cajaApellidosUsuario;
    private javax.swing.JTextField cajaNombresUsuario;
    private javax.swing.JPasswordField cajaPasswordRg;
    private javax.swing.JTextField cajaUsuarioRg;
    private javax.swing.JLabel imagenRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel txtContraseña;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
